def get_universal_features_from_binary_combined_features():
    pass


def get_universal_features_from_ternary_combined_features():
    pass


# "Entry	Formula
# INT_UNI_shortest_homoatomic_dist
# INT_UNI_shortest_heteroatomic_dist
# INT_UNI_shortest_homoatomic_dist_by_2_by_atom_size
# INT_UNI_shortest_heteroatomic_dist_by_sum_of_atom_sizes
# INT_UNI_shortest_homoatomic_dist_by_2_by_refined_atom_size
# INT_UNI_shortest_heteroatomic_dist_by_sum_of_refined_atom_sizes
# INT_UNI_highest_refined_percent_diff_abs
# INT_UNI_lowest_refined_percent_diff_abs
# INT_UNI_packing_efficiency
# WYC_UNI_lowest_wyckoff_elements
# CN_AVG_coordination_number
# CN_AVG_polyhedron_volume
# CN_AVG_central_atom_to_center_of_mass_dist
# CN_AVG_number_of_edges
# CN_AVG_number_of_faces
# CN_AVG_shortest_distance_to_face
# CN_AVG_shortest_distance_to_edge
# CN_AVG_volume_of_inscribed_sphere
# CN_AVG_packing_efficiency
# CN_MIN_coordination_number
# CN_MIN_polyhedron_volume
# CN_MIN_central_atom_to_center_of_mass_dist
# CN_MIN_number_of_edges
# CN_MIN_number_of_faces
# CN_MIN_shortest_distance_to_face
# CN_MIN_shortest_distance_to_edge
# CN_MIN_volume_of_inscribed_sphere
# CN_MIN_packing_efficiency
# CN_MAX_coordination_number
# CN_MAX_polyhedron_volume
# CN_MAX_central_atom_to_center_of_mass_dist
# CN_MAX_number_of_edges
# CN_MAX_number_of_faces
# CN_MAX_shortest_distance_to_face
# CN_MAX_shortest_distance_to_edge
# CN_MAX_volume_of_inscribed_sphere
# CN_MAX_packing_efficiency"
